### ISSUE TITLE
Margin Options not available

### ISSUE THREAD

**Issue by maluramichael** [pontedilana/WeasyPrintBundle#10]
I used knpsnappy before and there i could pass margin as an option to wkhtmltopdf. Is this unsupported by weasyprint or the weasyprint bundle? Because this call throws an error that margin-* is not available.

```
$this->generator->generateFromHtml(
    $renderedHTML,
    $pdfTempPath,
    [
        'margin-bottom' => 20,
        'margin-left'   => 0,
        'margin-right'  => 0,
        'margin-top'    => 0,
    ],
    true
);
```

**Comment by endelwar** [comment]
In [WeasyPrint documentation](https://doc.courtbouillon.org/weasyprint/stable/common_use_cases.html#adjust-document-dimensions) is stated that

> WeasyPrint does not provide support for adjusting page size or document margins via command-line flags. This is best accomplished with the CSS @page at-rule

You should move this margin configuration to your css file.

See also https://github.com/pontedilana/WeasyPrintBundle/issues/4 for other tips on migration from wkhtmltopdf
