### ISSUE TITLE
Redundant check in WeasyPrintResponse

### ISSUE THREAD

**Issue by garak** [pontedilana/WeasyPrintBundle#15]
The current implementation of WeasyPrintResponse performs a check against the content-disposition (to verify that a valid value is passed).
But the same check is already applied in the parent Response by Symfony itself, see https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/HttpFoundation/HeaderUtils.php#L165

I can propose a fixing PR.

**Comment by endelwar** [comment]
You're right, please send a PR
