### ISSUE TITLE
WeasyPrintBundle 1.4 is not compatible with php-weasyprint ^1.0

### ISSUE THREAD

**Issue by romainf** [pontedilana/WeasyPrintBundle#5]
Hi,

In WeasyPrintBundle 1.4, the bundle try to create the service "weasyprint.image", but this service does no longer exists in php-weasyprint ^1.0. This version shouldn't be accepted for this release.

**Comment by endelwar** [comment]
Hi @romainf,
you're right, I forgot to remove 1.0 support in 1.4.0 release, I've just released a fix as 1.4.1

Sorry for any inconvenience caused.
